rails_projects/alpha-blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'

end

rails_projects/alpha-blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_projects/alpha-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails_projects/alpha-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'standard'
  
  def home
  end

  def about
  end

end

rails_projects/alpha-blog/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_projects/alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_projects/alpha-blog/app/views/layouts/standard.html.erb
<html xmlns = "http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
    <meta http-equiv = "Content-Language" content = "en-us" />
    <title>Alpha Blog</title>
    <%= stylesheet_link_tag "style" %>
  </head>

  <body id = 'alphaBlog'>
    <div id = 'container'>
      <div id = 'header'>
        <h1>Alpha Blog</h1>
        <h3>Assignment for Ruby on Rails</h3>
      </div>

      <div id = 'content'>
        <%= yield -%>
      </div>

      <div id = 'sidebar'></div>

    </div>    
  </body>
</html>

rails_projects/alpha-blog/app/views/pages/about.html.erb
<h1>This is the About page</h1>

<%= link_to 'Go back to the Homepage', pages_home_path %> 

rails_projects/alpha-blog/app/views/pages/home.html.erb
<h1> This is the home page </h1>

<p id=generalDescription>Lorem ipsum, general description goes here</p>
<p id=secondaryDescription>More paragraphs would go here with extra information</p>

<%= link_to 'About', pages_about_path %>